[package]
name = "Rinoco"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet"}
#Sui = { local = "/home/mentalist/sui/crates/sui-framework/packages/sui-framework" }

[addresses]
rinoco = "0x0"
rinoco_treasury = "0xfb9d4d41b2214a5f370e5f899359040b0b2afe534e9e8eed35c9e0d1fecd45e1"